### ISSUE TITLE
0 vs. Nil for smallest / stopped process

### ISSUE THREAD

**Issue by dckc** [JoshOrndorff/LearnRholangByExample#1]
> `0` The smallest possible process. It literally means "do nothing".

In some grammars, 0 is a symbol for the stopped process. Not so in rholang. The stopped process is written `Nil`. The `0` process is an integer value.

I'm not sure it makes much difference...

**Comment by JoshOrndorff** [comment]
Thanks.

Fixed in 71a84338fe969bf
