### ISSUE TITLE
Visual corrections

### ISSUE THREAD

**Issue by jeremybeal11** [JoshOrndorff/LearnRholangByExample#3]
i think you should consider about having a visual breakdown of the code that shows the user what it looks like to print "Hello World" along with the definitions you defined. See example:
![img_1606](https://user-images.githubusercontent.com/23203842/45718106-f3bcd880-bb69-11e8-98b2-7b6f4df346e1.jpg)

**Comment by Viraculous** [comment]
@jeremybeal11 I thinks this chart is helpful. Could there be a clearer visual aid? This one is kinda rough

**Comment by jeremybeal11** [comment]
@Viraculous this is just a draft. i have already spoke with @JoshOrndorff  about it and i believe this will be more refined when we hit that bridge

**Comment by Viraculous** [comment]
Awesome

**Comment by JoshOrndorff** [comment]
I like this idea, but some of the suggested labels don't fully make sense. If anyone can create a nicer version I'll happily include it. Extra Credit for a PR, but dropping it here is also fine.

**Comment by jeremybeal11** [comment]
@JoshOrndorff  i will work on it. now that i have learned more about Rholang i can clarify those points. for instance: i didnt know what "new" was at the time so i assumed it was declaring a variable not creating an "unforgeable" name for that channel.
