### ISSUE TITLE
Ch 1 Exercises confusion

### ISSUE THREAD

**Issue by TrenchFloat** [JoshOrndorff/LearnRholangByExample#37]
I was able to make stdout say "Rholang Rocks!" but was confused once I tried to replace "stdout" with "someChannel". I later found out I wasn't supposed to succeed in having anything print to the screen, but in the meantime felt like I wasn't getting the exercise right. "Any results?" was a hint, but too subtle for me to catch.

Now I'm confused how I make "Sup World" print to the screen if someChannel won't go to the screen in the first place.

I suggest these exercises go after the "So where do the other channels go then? Nowhere! Not yet anyway." and before the tupleSpace.rho example exercise to avoid frustration at the outset.

**Comment by TrenchFloat** [comment]
After I learned to take out the quotations around someChannel:
![screenshot-rchain cloud-2018 10 26-10-17-54](https://user-images.githubusercontent.com/12161484/47575799-80e11300-d908-11e8-815a-1726280ecdee.png)

**Comment by JoshOrndorff** [comment]
Excellent feedback. Thank you!

Those exercises made more sense in older versions of rholang when printing to the screen was like
```rholang
@"stdout"!("Hello World")
```

I decided to just remove them entirely in 3ecf7d6bec

Keep the feedback comint
