### ISSUE TITLE
Adding a zip file with all of the .rho exercises 

### ISSUE THREAD

**Issue by jeremybeal11** [JoshOrndorff/LearnRholangByExample#7]
If you have the files, can you make a .ZIP with all of the exercises in it and add them to an exercise folder in the tutorial? My thought behind this is to make it simpler for those who wants to stay in the RNode env to run the exercises in the standalone mode and have all of the files there. I can add the documentation in the 0-Developement Env folder on how to transfer the files and extract them.  In addition, all they have to do is type: rnode eval ~/Rholang/<the_excersise_they_are_on>.rho as they are reading alongside the tutorial. 

***This is just an idea. We don't have to do this at all. its just, i find myself having to create new .rho files into my node just to test in the RNode env.***

**Comment by JoshOrndorff** [comment]
Anyone who clones the repo will have all the files. Learners who are nota fmiliar with git can download the zip from https://github.com/JoshOrndorff/LearnRholangByExample/archive/master.zip which I get like in this screenshot.

![image](https://user-images.githubusercontent.com/2915325/46433535-1bda3900-c71f-11e8-99c0-3d528b7fa4d5.png)
